import { Identifiable } from './utils';

/**
 * Represents a public invitation record in the signature chain
 * Created when:
 * 1. An admin (Alice) invites a new user (Bob)
 * 2. A user's device invites another device (e.g., Bob's laptop inviting Bob's phone)
 */
export interface InvitationInfo extends Identifiable {
    /** Unique identifier for the invitation, encoded in Base58 */
    $id: string

    /** 
     * Public signing key derived from the secret invitation key
     * Used to verify the invitation proof during acceptance
     */
    publicKey: string

    /** 
     * Timestamp when the invitation expires
     * Value of 0 indicates no expiration
     */
    expiration: number

    /** 
     * Maximum number of times this invitation can be used
     * Value of 0 indicates unlimited uses
     */
    maxUses: number

    /** 
     * Optional user ID for device invitations
     * Only present when inviting additional devices for an existing user
     */
    userId?: string
}

/**
 * Represents the current state of an invitation in the Team state
 * Extends the base Invitation type with usage tracking and revocation status
 */
export interface InvitationState extends InvitationInfo {
    /** Counter tracking how many times this invitation has been used */
    uses: number

    /** 
     * Indicates if the invitation was revoked
     * Once true, the invitation can no longer be used even if not expired
     */
    revoked: boolean
}

/**
 * Represents the proof document presented by an invitee during first connection
 * Used to verify the legitimacy of the invitation claim
 */
export interface ProofOfInvitationInfo extends Identifiable {
    /** 
     * Matches the id of the original invitation
     * Used to look up the corresponding invitation record
     */
    $id: string

    /** 
     * Cryptographic signature proving invitation ownership
     * Signs the combination of userId and invitation id using the derived private key
     */
    signature: string
}

/**
 * Represents an invitation for a new member to join a team
 * Includes the team ID and the invitation seed
 */
export type MemberInvitation = {
    teamId: string;
    invitationSeed: string;
}

/**
 * Represents an invitation for a new device to join a team
 * Includes the team ID, the invitation seed, and the user ID
 */
export type DeviceInvitation = MemberInvitation & {
    userId: string;
}

/**
 * Represents an invitation for a new member or device to join a team
 * Can be either a MemberInvitation or a DeviceInvitation
 */
export type TeamInvitation = MemberInvitation | DeviceInvitation;

/**
 * Represents the result of creating a new invitation
 * Contains the invitation identifier and the secret seed used to generate it
 */
export type InvitationResult = {
    /** Unique identifier for the invitation, encoded in Base58 */
    id: string
  
    /** 
     * Secret key used to generate the invitation
     * This seed is only returned when automatically generated by the system
     */
    seed: string
}