import inquirer from 'inquirer';
import chalk from 'chalk';
import fs from 'fs';
import path from 'path';
import { execSync } from 'child_process';

interface SetupConfig {
  storage: 'redb' | 'postgres' | 'null';
  installK6: boolean;
  devContainer: boolean;
}

interface SetupOptions {
  yes?: boolean;
}

async function setup(options: SetupOptions) {
  console.log(chalk.bold('\n TopGun Setup Wizard\n'));

  let config: SetupConfig = {
    storage: 'redb',
    installK6: false,
    devContainer: false,
  };

  // Interactive mode (unless --yes)
  if (!options.yes) {
    const answers = await inquirer.prompt([
      {
        type: 'list',
        name: 'storage',
        message: 'Storage backend:',
        choices: [
          {
            name: 'redb (recommended — embedded, zero dependencies, boots instantly)',
            value: 'redb',
          },
          { name: 'PostgreSQL (production use, requires Docker or external DB)', value: 'postgres' },
          { name: 'null (ephemeral, data lost on restart — for testing)', value: 'null' },
        ],
        default: 'redb',
      },
      {
        type: 'confirm',
        name: 'installK6',
        message: 'Install k6 for load testing? (requires Docker)',
        default: false,
      },
      {
        type: 'confirm',
        name: 'devContainer',
        message: 'Configure Dev Container for VS Code/Codespaces?',
        default: false,
      },
    ]);
    config = { ...config, ...(answers as Partial<SetupConfig>) };
  }

  // Step 1: Create .env file
  console.log(chalk.cyan('\n[1/4] Creating .env file...'));
  const envContent = generateEnvFile(config);
  fs.writeFileSync(path.join(process.cwd(), '.env'), envContent);
  console.log(chalk.green('  ✓ .env created'));

  // Inform the user which auth mode was written and how to switch
  if (config.storage !== 'postgres') {
    console.log(
      chalk.gray(
        '  Auth: TOPGUN_NO_AUTH=1 (local dev mode — set JWT_SECRET for any networked/production deployment)',
      ),
    );
  }
  console.log(chalk.gray(`  Storage: STORAGE_BACKEND=${config.storage}`));

  // Step 2: Install dependencies
  console.log(chalk.cyan('\n[2/4] Installing dependencies...'));
  if (!fs.existsSync(path.join(process.cwd(), 'node_modules'))) {
    try {
      execSync('pnpm install', { stdio: 'inherit' });
      console.log(chalk.green('  ✓ Dependencies installed'));
    } catch {
      console.error(chalk.red('  ✗ Failed to install dependencies'));
      process.exit(1);
    }
  } else {
    console.log(chalk.green('  ✓ Dependencies already installed'));
  }

  // Step 3: Build server binary if missing
  console.log(chalk.cyan('\n[3/4] Building server binary...'));
  const rustBinaryPath = path.join(process.cwd(), 'target/release/topgun-server');
  if (!fs.existsSync(rustBinaryPath)) {
    try {
      execSync('cargo build --release -p topgun-server --bin topgun-server', { stdio: 'inherit' });
      console.log(chalk.green('  ✓ Server binary built'));
    } catch {
      console.error(chalk.red('  ✗ Failed to build server binary'));
      console.log(chalk.yellow('  Hint: Make sure Rust toolchain is installed (https://rustup.rs)'));
      process.exit(1);
    }
  } else {
    console.log(chalk.green('  ✓ Server binary already built'));
  }

  // Step 4: Start PostgreSQL (if selected)
  if (config.storage === 'postgres') {
    console.log(chalk.cyan('\n[4/4] Starting PostgreSQL...'));
    try {
      execSync('docker compose up -d postgres', { stdio: 'inherit' });
      console.log(chalk.green('  ✓ PostgreSQL started'));

      console.log(chalk.gray('  Waiting for PostgreSQL to be ready...'));
      await waitForPostgres();
      console.log(chalk.green('  ✓ PostgreSQL is ready'));
    } catch {
      console.error(chalk.red('  ✗ Failed to start PostgreSQL'));
      console.log(chalk.yellow('  Hint: Make sure Docker is running'));
      process.exit(1);
    }
  } else {
    const storageLabel = config.storage === 'null' ? 'ephemeral in-memory' : 'embedded redb';
    console.log(chalk.cyan(`\n[4/4] Skipping database (${storageLabel} mode)`));
    console.log(chalk.green(`  ✓ ${storageLabel.charAt(0).toUpperCase() + storageLabel.slice(1)} storage will be used`));
  }

  // Done!
  console.log(chalk.bold.green('\n Setup complete!\n'));
  console.log(chalk.white('  Run:'));
  console.log(chalk.cyan('    npx @topgunbuild/cli dev'));
  console.log(chalk.white('\n  Server will start at http://localhost:8080\n'));
}

function generateEnvFile(config: SetupConfig): string {
  const lines = [
    '# TopGun Configuration',
    `# Generated by 'topgun setup' on ${new Date().toISOString()}`,
    '',
    '# Auth',
    '# local dev runs without auth tokens; set JWT_SECRET for any networked/production deployment',
    'TOPGUN_NO_AUTH=1',
    '',
    '# Storage',
    `STORAGE_BACKEND=${config.storage}`,
  ];

  if (config.storage === 'postgres') {
    lines.push('DB_HOST=localhost');
    lines.push('DB_PORT=5432');
    lines.push('DB_USER=topgun');
    lines.push('DB_PASSWORD=topgun_dev');
    lines.push('DB_NAME=topgun');
    lines.push('DATABASE_URL=postgresql://topgun:topgun_dev@localhost:5432/topgun');
  }

  lines.push('');
  lines.push('# Server');
  lines.push('PORT=8080');
  lines.push('METRICS_PORT=9091');
  lines.push('');
  lines.push('# Logging (optional)');
  lines.push('# TOPGUN_LOG_FORMAT=json  # json or omit for human-readable');
  lines.push('# LOG_LEVEL=debug');
  lines.push('');
  lines.push('# Admin (optional)');
  lines.push('# TOPGUN_ADMIN_USERNAME=admin');
  lines.push('# TOPGUN_ADMIN_PASSWORD=changeme');
  lines.push('# TOPGUN_ADMIN_DIR=./admin/dist');

  return lines.join('\n') + '\n';
}

async function waitForPostgres(maxAttempts = 30) {
  for (let i = 0; i < maxAttempts; i++) {
    try {
      execSync('docker compose exec -T postgres pg_isready -U topgun', {
        stdio: 'ignore',
      });
      return;
    } catch {
      await new Promise((r) => setTimeout(r, 1000));
    }
  }
  throw new Error('PostgreSQL did not become ready');
}

export default setup;
