import * as fs from 'fs';
import * as path from 'path';
import type { JsonFieldType, JsonMapSchema, JsonSchemaFile } from './types';
import { SchemaRegistry } from './dsl';

export interface CodegenOptions {
  /** Path to the topgun.schema.ts file. Default: './topgun.schema.ts' */
  schemaPath?: string;
  /** Output directory for generated files. Default: './generated' */
  outDir?: string;
  /** Generate TypeScript types file. Default: true */
  typescript?: boolean;
  /** Generate JSON intermediate file. Default: true */
  json?: boolean;
}

/**
 * Map a JsonFieldType to its TypeScript representation.
 * Produces concrete types: string[], number[][], etc.
 */
function mapFieldTypeToTs(fieldType: JsonFieldType): string {
  if (fieldType === 'String') return 'string';
  if (fieldType === 'Int') return 'number';
  if (fieldType === 'Float') return 'number';
  if (fieldType === 'Bool') return 'boolean';
  if (fieldType === 'Binary') return 'Uint8Array';
  if (fieldType === 'Timestamp') return 'number';
  if (fieldType === 'Map') return 'Record<string, unknown>';
  if (fieldType === 'Any') return 'unknown';
  if (typeof fieldType === 'object' && 'Array' in fieldType) {
    return `${mapFieldTypeToTs(fieldType.Array)}[]`;
  }
  return 'unknown';
}

/**
 * Derive a TypeScript interface name from a map name.
 * Rule: strip trailing 's' (if present) to singularize, apply PascalCase, append 'Record'.
 * Examples: users -> UserRecord, posts -> PostRecord, metadata -> MetadataRecord,
 *           people -> PeopleRecord (no trailing 's' to strip)
 */
function mapNameToInterfaceName(mapName: string): string {
  let singular = mapName;
  if (singular.endsWith('s')) {
    singular = singular.slice(0, -1);
  }
  // Apply PascalCase: capitalize first letter
  const pascal = singular.charAt(0).toUpperCase() + singular.slice(1);
  return `${pascal}Record`;
}

/**
 * Generate a TypeScript types file from registered schemas.
 */
function generateTypescript(schemas: Record<string, JsonMapSchema>): string {
  const lines: string[] = [
    '// Generated by @topgunbuild/schema codegen — do not edit manually',
    '',
  ];

  const mapNames = Object.keys(schemas);

  for (const mapName of mapNames) {
    const mapSchema = schemas[mapName];
    const interfaceName = mapNameToInterfaceName(mapName);

    lines.push(`export interface ${interfaceName} {`);
    for (const field of mapSchema.fields) {
      const tsType = mapFieldTypeToTs(field.field_type);
      const optionalMark = field.required ? '' : '?';
      lines.push(`  ${field.name}${optionalMark}: ${tsType};`);
    }
    lines.push('}');
    lines.push('');
  }

  // MapSchemas union type
  if (mapNames.length > 0) {
    lines.push('export interface MapSchemas {');
    for (const mapName of mapNames) {
      const interfaceName = mapNameToInterfaceName(mapName);
      lines.push(`  ${mapName}: ${interfaceName};`);
    }
    lines.push('}');
    lines.push('');
  }

  return lines.join('\n');
}

/**
 * Load a schema file and return the global SchemaRegistry schemas.
 * The schema file must call schema.register(...) using SchemaRegistry.global.
 */
function loadSchemaFile(schemaPath: string): Record<string, JsonMapSchema> {
  const absolutePath = path.resolve(schemaPath);

  if (!fs.existsSync(absolutePath)) {
    throw new Error(`Schema file not found: ${absolutePath}`);
  }

  // Reset the global registry before loading so successive runs are clean
  const registry = SchemaRegistry.global as unknown as { _schemas: Record<string, JsonMapSchema> };
  for (const key of Object.keys(registry._schemas)) {
    delete registry._schemas[key];
  }

  // Load the schema file (ts-node/tsx must be registered by the caller for .ts files)
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  require(absolutePath);

  return SchemaRegistry.global.getSchemas();
}

/**
 * Run codegen: load schema file, write JSON and/or TypeScript output files.
 */
export function runCodegen(options: CodegenOptions = {}): void {
  const {
    schemaPath = './topgun.schema.ts',
    outDir = './generated',
    typescript = true,
    json = true,
  } = options;

  const schemas = loadSchemaFile(schemaPath);

  const absoluteOutDir = path.resolve(outDir);
  if (!fs.existsSync(absoluteOutDir)) {
    fs.mkdirSync(absoluteOutDir, { recursive: true });
  }

  const generated: string[] = [];

  if (json) {
    const schemaFile: JsonSchemaFile = { maps: schemas };
    const jsonPath = path.join(absoluteOutDir, 'topgun.schema.json');
    fs.writeFileSync(jsonPath, JSON.stringify(schemaFile, null, 2), 'utf-8');
    generated.push(jsonPath);
  }

  if (typescript) {
    const tsContent = generateTypescript(schemas);
    const tsPath = path.join(absoluteOutDir, 'topgun.types.ts');
    fs.writeFileSync(tsPath, tsContent, 'utf-8');
    generated.push(tsPath);
  }

  console.log(`Generated ${generated.length} file(s):`);
  for (const file of generated) {
    console.log(`  ${file}`);
  }
}
