import { Server as HttpServer } from 'http';
import { Server as HttpsServer } from 'https';
import { WebSocketServer } from 'ws';
import { HLC, PermissionType, Principal } from '@topgunbuild/core';
import { MetricsService } from './monitoring/MetricsService';
import { ConnectionManager } from './coordinator/connection-manager';
import { StorageManager } from './coordinator/storage-manager';
import { QueryRegistry } from './query/QueryRegistry';
import { ClusterManager } from './cluster/ClusterManager';
import { PartitionService } from './cluster/PartitionService';
import { ReplicationPipeline } from './cluster/ReplicationPipeline';
import { LockManager } from './cluster/LockManager';
import { TopicManager } from './topic/TopicManager';
import { SecurityManager } from './security/SecurityManager';
import { AuthHandler } from './coordinator';
import { OperationHandler } from './coordinator';
import { WebSocketHandler } from './coordinator';
import { LifecycleManager } from './coordinator';
import { BroadcastHandler } from './coordinator';
import { GCHandler } from './coordinator';
import { ClusterEventHandler } from './coordinator';
import { HeartbeatHandler } from './coordinator';
import { ClientMessageHandler } from './coordinator';
import { PersistenceHandler } from './coordinator';
import { OperationContextHandler } from './coordinator';
import { QueryConversionHandler } from './coordinator';
import { BatchProcessingHandler } from './coordinator';
import { WriteConcernHandler } from './coordinator';
import { LockHandler } from './coordinator';
import { TopicHandler } from './coordinator';
import { PartitionHandler } from './coordinator';
import { SearchHandler } from './coordinator';
import { JournalHandler } from './coordinator';
import { CounterHandler } from './handlers/CounterHandler';
import { EntryProcessorHandler } from './handlers/EntryProcessorHandler';
import { ConflictResolverHandler } from './handlers/ConflictResolverHandler';
import { EventJournalService } from './EventJournalService';
import { PartitionReassigner } from './cluster/PartitionReassigner';
import { ReadReplicaHandler } from './cluster/ReadReplicaHandler';
import { MerkleTreeManager } from './cluster/MerkleTreeManager';
import { RepairScheduler } from './cluster/RepairScheduler';
import { SearchCoordinator, ClusterSearchCoordinator } from './search';
import { DistributedSubscriptionCoordinator } from './subscriptions/DistributedSubscriptionCoordinator';
import { DebugEndpoints } from './debug';
import { BootstrapController } from './bootstrap';
import { SettingsController } from './settings';
import { MessageRegistry } from './coordinator/message-registry';
import { StripedEventExecutor } from './utils/StripedEventExecutor';
import { BackpressureRegulator } from './utils/BackpressureRegulator';
import { CoalescingWriterOptions } from './utils/CoalescingWriter';
import { ConnectionRateLimiter } from './utils/ConnectionRateLimiter';
import { RateLimitedLogger } from './utils/RateLimitedLogger';
import { WorkerPool, MerkleWorker, CRDTMergeWorker, SerializationWorker } from './workers';
import { ObjectPool, PooledEventPayload } from './memory';
import { TaskletScheduler } from './tasklet';
import { WriteAckManager } from './ack/WriteAckManager';

export interface ServerDependencies {
    hlc: HLC;
    metricsService: MetricsService;
    securityManager: SecurityManager;
    eventExecutor: StripedEventExecutor;
    backpressure: BackpressureRegulator;
    writeCoalescingOptions: Partial<CoalescingWriterOptions>;
    connectionManager: ConnectionManager;
    cluster: ClusterManager;
    partitionService: PartitionService;
    storageManager: StorageManager;
    queryRegistry: QueryRegistry;
    eventPayloadPool: ObjectPool<PooledEventPayload>;
    taskletScheduler: TaskletScheduler;
    writeAckManager: WriteAckManager;
    rateLimiter: ConnectionRateLimiter;
    authHandler: AuthHandler;
    rateLimitedLogger: RateLimitedLogger;
    workerPool?: WorkerPool;
    merkleWorker?: MerkleWorker;
    crdtMergeWorker?: CRDTMergeWorker;
    serializationWorker?: SerializationWorker;
    httpServer: HttpServer | HttpsServer;
    debugEndpoints?: DebugEndpoints;
    bootstrapController: BootstrapController;
    settingsController: SettingsController;
    metricsServer: HttpServer;
    wss: WebSocketServer;
    replicationPipeline?: ReplicationPipeline;
    lockManager: LockManager;
    topicManager: TopicManager;
    counterHandler: CounterHandler;
    entryProcessorHandler: EntryProcessorHandler;
    conflictResolverHandler: ConflictResolverHandler;
    eventJournalService?: EventJournalService;
    partitionReassigner?: PartitionReassigner;
    readReplicaHandler?: ReadReplicaHandler;
    merkleTreeManager?: MerkleTreeManager;
    repairScheduler?: RepairScheduler;
    searchCoordinator: SearchCoordinator;
    clusterSearchCoordinator?: ClusterSearchCoordinator;
    distributedSubCoordinator?: DistributedSubscriptionCoordinator;
    pendingBatchOperations: Set<Promise<void>>;
    jwtSecret: string;
    broadcastHandler: BroadcastHandler;
    heartbeatHandler: HeartbeatHandler;
    persistenceHandler: PersistenceHandler;
    operationContextHandler: OperationContextHandler;
    lockHandler: LockHandler;
    topicHandler: TopicHandler;
    partitionHandler: PartitionHandler;
    searchHandler: SearchHandler;
    journalHandler: JournalHandler;
    operationHandler: OperationHandler;
    webSocketHandler: WebSocketHandler;
    clientMessageHandler: ClientMessageHandler;
    gcHandler: GCHandler;
    queryConversionHandler: QueryConversionHandler;
    batchProcessingHandler: BatchProcessingHandler;
    writeConcernHandler: WriteConcernHandler;
    clusterEventHandler: ClusterEventHandler;
    messageRegistry: MessageRegistry;
    lifecycleManager: LifecycleManager;
}
